### ISSUE TITLE
Change environment functionality

### ISSUE THREAD

**Issue by abdallahshaban557** [poyashad/display-aws-amplify-env-vscode-extension#1]
Hi @poyashad,

It would be great if the extension allows developers to change the active Amplify environment on their local machine! Thank you for the great work on this extension!

**Comment by poyashad** [comment]
Thanks @abdallahshaban557 I will take a look at it!

**Comment by poyashad** [comment]
We now have a feature that allows developers to change the active Amplify Environment! 
<img width="727" alt="Skärmavbild 2022-05-16 kl  01 51 57" src="https://user-images.githubusercontent.com/20397026/168499948-5030c752-82e3-4651-97af-a094278caf0e.png">

**Comment by abdallahshaban557** [comment]
That is awesome! Thank you, Poya!
