### ISSUE TITLE
Using commands from the extension should not create a new terminal screen everytime

### ISSUE THREAD

**Issue by abdallahshaban557** [poyashad/display-aws-amplify-env-vscode-extension#2]
Hi @poyashad ,

It would be great if while using commands from the extension, that a new terminal screen would not be created every single time.

You can see in the source code it uses vscode.window.createTerminal to run the Amplify CLI. Instead maybe you could run the command as a child process of the extension.

```
import * as cp from "child_process";

const execShell = (cmd: string) =>
    new Promise<string>((resolve, reject) => {
        cp.exec(cmd, (err, out) => {
            if (err) {
                return reject(err);
            }
            return resolve(out);
        });
    });
```

Here is a Stackoverflow post with the same issue https://stackoverflow.com/questions/43007267/how-to-run-a-system-command-from-vscode-extension

**Comment by poyashad** [comment]
Hi @abdallahshaban557, with this new update. if you change the environment, the extension uses a child process. Thank you very much for pointing this out! As for the other commands in the extension. They show a lot of information that I think is useful to the user, but let me know what you think! Thanks for your feedback
![demo1](https://user-images.githubusercontent.com/20397026/169777690-95e665c8-2741-44e3-9f96-bd65166178e4.gif)

**Comment by abdallahshaban557** [comment]
Thank you, Poya! Loving this new feature! Closing this request out!
